### ISSUE TITLE
Ring only when the shutdown is enabled

### ISSUE THREAD

**Issue by davidgatti** [0x4447/0x4447_product_maintenance#1]
When the shutdown is set, the system will propagate a message to any session which will ring the bell, this is cool when the shutdown is set, so you can go to the terminal and move the cursor. 

But then it be nice to suppress the next ring, when the shutdown is removed - since it is unnecessary, and just distracting.

**Comment by ScriptMyJob** [comment]
https://github.com/0x4447/0x4447_product_maintenance/pull/3
